FROM python:3.9

RUN mkdir /app/
WORKDIR /app/ 

RUN pip3 install redis
RUN pip3 install hotqueue
RUN pip3 install matplotlib
RUN pip3 install Flask

COPY ./src/* /app/

ENTRYPOINT ["python3"]
CMD ["worker.py"]
