FROM python:3.9

RUN mkdir /app
WORKDIR /app 

RUN pip3 install Flask==2.0.3 \
                 redis==4.1.4 \
                 hotqueue==0.2.8

COPY ./src/* /app/
COPY ./comets_data.json /app/comets_data.json

ENTRYPOINT ["python3"]
CMD ["flask_api.py"]
