FROM python:3.9

RUN mkdir /app
WORKDIR /app 

RUN pip3 install --user Flask==2.0.3
RUN pip3 install --user redis
RUN pip3 install --user hotqueue

COPY ./src/* /app/

ENTRYPOINT ["python3"]
CMD ["flask_api.py"]
